//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PaperImage.rc
//
#define IDC_REDRAW                      2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_INDICATOR_XY                 101
#define ID_INDICATOR_RC                 102
#define ID_INDICATOR_MXY                103
#define ID_INDICATOR_CXY                104
#define ID_INDICATOR_RATE               105
#define IDR_MAINFRAME                   128
#define IDR_PaperImageTYPE              130
#define IDD_CCQDIALOG                   310
#define IDD_SIMULDLG                    311
#define IDD_CCQDIALOG2                  313
#define IDB_BITMAP2                     314
#define IDC_RADIO1                      1000
#define IDC_RADIO2                      1001
#define IDC_RADIO3                      1002
#define IDC_EDIT_REO_COUNT              1051
#define IDC_EDIT_RFO_COUNT              1052
#define IDC_EDIT_REO_PERCENT            1053
#define IDC_EDIT_RFO_PERCENT            1054
#define IDC_EDIT_RLSO_PERCENT           1055
#define IDC_EDIT_RMSO_PERCENT           1056
#define IDC_EDIT_RHSO_PERCENT           1057
#define IDC_EDIT_REOCQ_PERCENT          1058
#define IDC_EDIT_REONCQ_PERCENT         1059
#define IDC_EDIT_REOCQ_COUNT            1060
#define IDC_EDIT_REONCQ_COUNT           1061
#define IDC_EDIT_NO_COUNT               1062
#define IDC_EDIT_RAO_PERCENT            1063
#define IDC_EDIT_RAO_REO_COUNT          1064
#define IDC_EDIT_RAO_RFO_COUNT          1065
#define IDC_EDIT_RAO_REO_RLSO           1066
#define IDC_EDIT_RAO_RFO_RLSO           1067
#define IDC_EDIT_RAO_REO_RMSO           1068
#define IDC_EDIT_RAO_RFO_RMSO           1069
#define IDC_EDIT_RAO_REO_RHSO           1070
#define IDC_EDIT_RAO_RFO_RHSO           1071
#define IDC_EDIT_RSVO_PERCENT           1072
#define IDC_EDIT_RFVO_PERCENT           1073
#define IDC_EDIT_RSMO_PERCENT           1074
#define IDC_EDIT_RSVO_REO_COUNT         1075
#define IDC_EDIT_RSVO_RFO_COUNT         1076
#define IDC_EDIT_RSVO_REO_RLSO          1077
#define IDC_EDIT_RSVO_RFO_RLSO          1078
#define IDC_EDIT_RSVO_REO_RMSO          1079
#define IDC_EDIT_RSVO_RFO_RMSO          1080
#define IDC_EDIT_RSVO_REO_RHSO          1081
#define IDC_EDIT_RSVO_RFO_RHSO          1082
#define IDC_EDIT_RFVO_REO_COUNT         1083
#define IDC_EDIT_RFVO_RFO_COUNT         1084
#define IDC_EDIT_RFVO_REO_RLSO          1085
#define IDC_EDIT_RFVO_RFO_RLSO          1086
#define IDC_EDIT_RFVO_REO_RMSO          1087
#define IDC_EDIT_RFVO_RFO_RMSO          1088
#define IDC_EDIT_RFVO_REO_RHSO          1089
#define IDC_EDIT_RFVO_RFO_RHSO          1090
#define IDC_EDIT_RSMO_REO_COUNT         1091
#define IDC_EDIT_RSMO_RFO_COUNT         1092
#define IDC_EDIT_RSMO_REO_RLSO          1093
#define IDC_EDIT_RSMO_RFO_RLSO          1094
#define IDC_EDIT_RSMO_REO_RMSO          1095
#define IDC_EDIT_RSMO_RFO_RMSO          1096
#define IDC_EDIT_RSMO_REO_RHSO          1097
#define IDC_EDIT_RSMO_RFO_RHSO          1098
#define IDC_EDIT_RFOCQ_PERCENT          1099
#define IDC_EDIT_RFONCQ_PERCENT         1100
#define IDC_CHECK_ALL                   1101
#define IDC_CHECK_RAO                   1102
#define IDC_CHECK_RAO_RLSO              1103
#define IDC_CHECK_RAO_RMSO              1104
#define IDC_CHECK_RAO_RHSO              1105
#define IDC_CHECK_RSVO                  1106
#define IDC_CHECK_RSVO_RLSO             1107
#define IDC_CHECK_RSVO_RMSO             1108
#define IDC_CHECK_RSVO_RHSO             1109
#define IDC_CHECK_RFVO                  1110
#define IDC_CHECK_RFVO_RLSO             1111
#define IDC_CHECK_RFVO_RMSO             1112
#define IDC_CHECK_RFVO_RHSO             1113
#define IDC_CHECK_RSMO                  1114
#define IDC_CHECK_RSMO_RLSO             1115
#define IDC_CHECK_RSMO_RMSO             1116
#define IDC_CHECK_RSMO_RHSO             1117
#define IDC_CHECK_REO                   1118
#define IDC_CHECK_RFO                   1119
#define IDC_CLOSE                       1120
#define ID_PLAY                         1121
#define IDC_EDIT_RFOCQ_COUNT            1121
#define IDC_EDIT_RFONCQ_COUNT           1122
#define IDC_PERCENT                     1123
#define IDC_COUNT                       1124
#define ID_RESET                        1125
#define IDC_CHECK_DRAWPATH              1126
#define IDC_EDIT_INTERVAL               1127
#define IDC_SLIDER1                     1128
#define IDC_CHECK_PATH                  1129
#define ID_CLOSE                        1130
#define IDC_COMBO_CQTYPE                1131
#define IDC_BUTTON1                     1132
#define ID_BUTTON_C1                    32771
#define ID_BUTTON32772                  32772
#define ID_BUTTON_GRID                  32772
#define ID_BUTTON_INIT                  32773
#define ID_BUTTON_C2                    32775
#define ID_BUTTON_C3                    32776
#define ID_BUTTON_C4                    32777
#define ID_BUTTON_C5                    32778
#define ID_BUTTON_C6                    32779
#define ID_BUTTON_C7                    32780
#define ID_BUTTON_DRAWMODE1             32781
#define ID_BUTTON_DRAWMODE2             32782
#define ID_BUTTON_PATHDOT               32783
#define ID_BUTTON_A1                    32787
#define ID_BUTTON_A2                    32788
#define ID_BUTTON_A3                    32789
#define ID_BUTTON_A4                    32790
#define ID_BUTTON_A5                    32791
#define ID_BUTTON_R1                    32792
#define ID_BUTTON_R2                    32793
#define ID_BUTTON_R3                    32794
#define ID_BUTTON_R4                    32795
#define ID_BUTTON_R5                    32796
#define ID_BUTTON_C                     32797
#define ID_BUTTON_A                     32799
#define ID_BUTTON_R                     32800
#define ID_BUTTON_S                     32801
#define ID_BUTTON_ZE                    32802
#define ID_32803                        32803

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1133
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
